# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from moving_object_msgs/MovingObject.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg
import sensor_msgs.msg

class MovingObject(genpy.Message):
  _md5sum = "cabc63dcb76cee6ba7670da10556e256"
  _type = "moving_object_msgs/MovingObject"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """# Copyright (c) 2017 Intel Corporation
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

int32 id                           # Object ID
string type                        # The object type detected in this roi
float32 probability                # The detection probability of object in this roi
sensor_msgs/RegionOfInterest roi   # region of interest
geometry_msgs/Point32 min          # min and max locate the diagonal of a bounding-box of the detected object whose
geometry_msgs/Point32 max          # x, y and z axis parellel to the axises correspondingly in camera coordinates
geometry_msgs/Point   velocity     # The velocity with which the roi moves.
================================================================================
MSG: sensor_msgs/RegionOfInterest
# This message is used to specify a region of interest within an image.
#
# When used to specify the ROI setting of the camera when the image was
# taken, the height and width fields should either match the height and
# width fields for the associated image; or height = width = 0
# indicates that the full resolution image was captured.

uint32 x_offset  # Leftmost pixel of the ROI
                 # (0 if the ROI includes the left edge of the image)
uint32 y_offset  # Topmost pixel of the ROI
                 # (0 if the ROI includes the top edge of the image)
uint32 height    # Height of ROI
uint32 width     # Width of ROI

# True if a distinct rectified ROI should be calculated from the "raw"
# ROI in this message. Typically this should be False if the full image
# is captured (ROI not used), and True if a subwindow is captured (ROI
# used).
bool do_rectify

================================================================================
MSG: geometry_msgs/Point32
# This contains the position of a point in free space(with 32 bits of precision).
# It is recommeded to use Point wherever possible instead of Point32.  
# 
# This recommendation is to promote interoperability.  
#
# This message is designed to take up less space when sending
# lots of points at once, as in the case of a PointCloud.  

float32 x
float32 y
float32 z
================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['id','type','probability','roi','min','max','velocity']
  _slot_types = ['int32','string','float32','sensor_msgs/RegionOfInterest','geometry_msgs/Point32','geometry_msgs/Point32','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       id,type,probability,roi,min,max,velocity

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(MovingObject, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.id is None:
        self.id = 0
      if self.type is None:
        self.type = ''
      if self.probability is None:
        self.probability = 0.
      if self.roi is None:
        self.roi = sensor_msgs.msg.RegionOfInterest()
      if self.min is None:
        self.min = geometry_msgs.msg.Point32()
      if self.max is None:
        self.max = geometry_msgs.msg.Point32()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Point()
    else:
      self.id = 0
      self.type = ''
      self.probability = 0.
      self.roi = sensor_msgs.msg.RegionOfInterest()
      self.min = geometry_msgs.msg.Point32()
      self.max = geometry_msgs.msg.Point32()
      self.velocity = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_i().pack(self.id))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f4IB6f3d().pack(_x.probability, _x.roi.x_offset, _x.roi.y_offset, _x.roi.height, _x.roi.width, _x.roi.do_rectify, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z, _x.velocity.x, _x.velocity.y, _x.velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.roi is None:
        self.roi = sensor_msgs.msg.RegionOfInterest()
      if self.min is None:
        self.min = geometry_msgs.msg.Point32()
      if self.max is None:
        self.max = geometry_msgs.msg.Point32()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 69
      (_x.probability, _x.roi.x_offset, _x.roi.y_offset, _x.roi.height, _x.roi.width, _x.roi.do_rectify, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z, _x.velocity.x, _x.velocity.y, _x.velocity.z,) = _get_struct_f4IB6f3d().unpack(str[start:end])
      self.roi.do_rectify = bool(self.roi.do_rectify)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(_get_struct_i().pack(self.id))
      _x = self.type
      length = len(_x)
      if python3 or type(_x) == unicode:
        _x = _x.encode('utf-8')
        length = len(_x)
      buff.write(struct.pack('<I%ss'%length, length, _x))
      _x = self
      buff.write(_get_struct_f4IB6f3d().pack(_x.probability, _x.roi.x_offset, _x.roi.y_offset, _x.roi.height, _x.roi.width, _x.roi.do_rectify, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z, _x.velocity.x, _x.velocity.y, _x.velocity.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.roi is None:
        self.roi = sensor_msgs.msg.RegionOfInterest()
      if self.min is None:
        self.min = geometry_msgs.msg.Point32()
      if self.max is None:
        self.max = geometry_msgs.msg.Point32()
      if self.velocity is None:
        self.velocity = geometry_msgs.msg.Point()
      end = 0
      start = end
      end += 4
      (self.id,) = _get_struct_i().unpack(str[start:end])
      start = end
      end += 4
      (length,) = _struct_I.unpack(str[start:end])
      start = end
      end += length
      if python3:
        self.type = str[start:end].decode('utf-8')
      else:
        self.type = str[start:end]
      _x = self
      start = end
      end += 69
      (_x.probability, _x.roi.x_offset, _x.roi.y_offset, _x.roi.height, _x.roi.width, _x.roi.do_rectify, _x.min.x, _x.min.y, _x.min.z, _x.max.x, _x.max.y, _x.max.z, _x.velocity.x, _x.velocity.y, _x.velocity.z,) = _get_struct_f4IB6f3d().unpack(str[start:end])
      self.roi.do_rectify = bool(self.roi.do_rectify)
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_i = None
def _get_struct_i():
    global _struct_i
    if _struct_i is None:
        _struct_i = struct.Struct("<i")
    return _struct_i
_struct_f4IB6f3d = None
def _get_struct_f4IB6f3d():
    global _struct_f4IB6f3d
    if _struct_f4IB6f3d is None:
        _struct_f4IB6f3d = struct.Struct("<f4IB6f3d")
    return _struct_f4IB6f3d
