//#line 2 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
//
// File autogenerated for the object_analytics_nodelet package
// by the dynamic_reconfigure package.
// Please do not edit.
//
// ********************************************************/

#ifndef __object_analytics_nodelet__ORGANIZEDMULTIPLANESEGMENTATIONCONFIG_H__
#define __object_analytics_nodelet__ORGANIZEDMULTIPLANESEGMENTATIONCONFIG_H__

#if __cplusplus >= 201103L
#define DYNAMIC_RECONFIGURE_FINAL final
#else
#define DYNAMIC_RECONFIGURE_FINAL
#endif

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace object_analytics_nodelet
{
  class OrganizedMultiPlaneSegmentationConfigStatics;

  class OrganizedMultiPlaneSegmentationConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l,
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }

      virtual void clamp(OrganizedMultiPlaneSegmentationConfig &config, const OrganizedMultiPlaneSegmentationConfig &max, const OrganizedMultiPlaneSegmentationConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const OrganizedMultiPlaneSegmentationConfig &config1, const OrganizedMultiPlaneSegmentationConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, OrganizedMultiPlaneSegmentationConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const OrganizedMultiPlaneSegmentationConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, OrganizedMultiPlaneSegmentationConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const OrganizedMultiPlaneSegmentationConfig &config) const = 0;
      virtual void getValue(const OrganizedMultiPlaneSegmentationConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template <class T>
    class ParamDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string a_name, std::string a_type, uint32_t a_level,
          std::string a_description, std::string a_edit_method, T OrganizedMultiPlaneSegmentationConfig::* a_f) :
        AbstractParamDescription(a_name, a_type, a_level, a_description, a_edit_method),
        field(a_f)
      {}

      T (OrganizedMultiPlaneSegmentationConfig::* field);

      virtual void clamp(OrganizedMultiPlaneSegmentationConfig &config, const OrganizedMultiPlaneSegmentationConfig &max, const OrganizedMultiPlaneSegmentationConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;

        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const OrganizedMultiPlaneSegmentationConfig &config1, const OrganizedMultiPlaneSegmentationConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, OrganizedMultiPlaneSegmentationConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const OrganizedMultiPlaneSegmentationConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, OrganizedMultiPlaneSegmentationConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const OrganizedMultiPlaneSegmentationConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const OrganizedMultiPlaneSegmentationConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, OrganizedMultiPlaneSegmentationConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    // Final keyword added to class because it has virtual methods and inherits
    // from a class with a non-virtual destructor.
    template<class T, class PT>
    class GroupDescription DYNAMIC_RECONFIGURE_FINAL : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string a_name, std::string a_type, int a_parent, int a_id, bool a_s, T PT::* a_f) : AbstractGroupDescription(a_name, a_type, a_parent, a_id, a_s), field(a_f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, OrganizedMultiPlaneSegmentationConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<OrganizedMultiPlaneSegmentationConfig::AbstractGroupDescriptionConstPtr> groups;
    };

class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(OrganizedMultiPlaneSegmentationConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("comparator"==(*_i)->name){comparator = boost::any_cast<int>(val);}
        if("min_cluster_size"==(*_i)->name){min_cluster_size = boost::any_cast<int>(val);}
        if("min_plane_inliers"==(*_i)->name){min_plane_inliers = boost::any_cast<int>(val);}
        if("normal_max_depth_change"==(*_i)->name){normal_max_depth_change = boost::any_cast<double>(val);}
        if("normal_angle_threshold"==(*_i)->name){normal_angle_threshold = boost::any_cast<double>(val);}
        if("normal_distance_threshold"==(*_i)->name){normal_distance_threshold = boost::any_cast<double>(val);}
        if("normal_smooth_size"==(*_i)->name){normal_smooth_size = boost::any_cast<double>(val);}
        if("euclidean_distance_threshold"==(*_i)->name){euclidean_distance_threshold = boost::any_cast<double>(val);}
        if("plane_minimum_points"==(*_i)->name){plane_minimum_points = boost::any_cast<int>(val);}
        if("object_minimum_points"==(*_i)->name){object_minimum_points = boost::any_cast<int>(val);}
      }
    }

    int comparator;
int min_cluster_size;
int min_plane_inliers;
double normal_max_depth_change;
double normal_angle_threshold;
double normal_distance_threshold;
double normal_smooth_size;
double euclidean_distance_threshold;
int plane_minimum_points;
int object_minimum_points;

    bool state;
    std::string name;

    
}groups;



//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int comparator;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_cluster_size;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int min_plane_inliers;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_max_depth_change;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_angle_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_distance_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double normal_smooth_size;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double euclidean_distance_threshold;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int plane_minimum_points;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      int object_minimum_points;
//#line 228 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("OrganizedMultiPlaneSegmentationConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }

    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }

    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const OrganizedMultiPlaneSegmentationConfig &__max__ = __getMax__();
      const OrganizedMultiPlaneSegmentationConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const OrganizedMultiPlaneSegmentationConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }

    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const OrganizedMultiPlaneSegmentationConfig &__getDefault__();
    static const OrganizedMultiPlaneSegmentationConfig &__getMax__();
    static const OrganizedMultiPlaneSegmentationConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();

  private:
    static const OrganizedMultiPlaneSegmentationConfigStatics *__get_statics__();
  };

  template <> // Max and min are ignored for strings.
  inline void OrganizedMultiPlaneSegmentationConfig::ParamDescription<std::string>::clamp(OrganizedMultiPlaneSegmentationConfig &config, const OrganizedMultiPlaneSegmentationConfig &max, const OrganizedMultiPlaneSegmentationConfig &min) const
  {
    (void) config;
    (void) min;
    (void) max;
    return;
  }

  class OrganizedMultiPlaneSegmentationConfigStatics
  {
    friend class OrganizedMultiPlaneSegmentationConfig;

    OrganizedMultiPlaneSegmentationConfigStatics()
    {
OrganizedMultiPlaneSegmentationConfig::GroupDescription<OrganizedMultiPlaneSegmentationConfig::DEFAULT, OrganizedMultiPlaneSegmentationConfig> Default("Default", "", 0, 0, true, &OrganizedMultiPlaneSegmentationConfig::groups);
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.comparator = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.comparator = 3;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.comparator = 0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("comparator", "int", 0, "Comparator to be used for segmentation", "{'enum_description': 'Comparator to be used for segmetation', 'enum': [{'srcline': 27, 'description': 'Plane Coefficient Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'PlaneCoefficientComparator'}, {'srcline': 28, 'description': 'Euclidean Plane Coefficient Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EuclideanPlaneCoefficientComparator'}, {'srcline': 29, 'description': 'RGB Plane Coefficient Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'RGBPlaneCoefficientComparator'}, {'srcline': 30, 'description': 'Edge Aware Plane Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EdgeAwarePlaneComparator'}]}", &OrganizedMultiPlaneSegmentationConfig::comparator)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("comparator", "int", 0, "Comparator to be used for segmentation", "{'enum_description': 'Comparator to be used for segmetation', 'enum': [{'srcline': 27, 'description': 'Plane Coefficient Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 0, 'ctype': 'int', 'type': 'int', 'name': 'PlaneCoefficientComparator'}, {'srcline': 28, 'description': 'Euclidean Plane Coefficient Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 1, 'ctype': 'int', 'type': 'int', 'name': 'EuclideanPlaneCoefficientComparator'}, {'srcline': 29, 'description': 'RGB Plane Coefficient Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 2, 'ctype': 'int', 'type': 'int', 'name': 'RGBPlaneCoefficientComparator'}, {'srcline': 30, 'description': 'Edge Aware Plane Comparator', 'srcfile': '/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg', 'cconsttype': 'const int', 'value': 3, 'ctype': 'int', 'type': 'int', 'name': 'EdgeAwarePlaneComparator'}]}", &OrganizedMultiPlaneSegmentationConfig::comparator)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_cluster_size = 10;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_cluster_size = 10000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_cluster_size = 300;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("min_cluster_size", "int", 0, "The minimum number of points that a cluster needs to contain in order to be considered valid", "", &OrganizedMultiPlaneSegmentationConfig::min_cluster_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("min_cluster_size", "int", 0, "The minimum number of points that a cluster needs to contain in order to be considered valid", "", &OrganizedMultiPlaneSegmentationConfig::min_cluster_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.min_plane_inliers = 100;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.min_plane_inliers = 10000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.min_plane_inliers = 1000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("min_plane_inliers", "int", 0, "The mininum number of inliers required for a plane", "", &OrganizedMultiPlaneSegmentationConfig::min_plane_inliers)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("min_plane_inliers", "int", 0, "The mininum number of inliers required for a plane", "", &OrganizedMultiPlaneSegmentationConfig::min_plane_inliers)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_max_depth_change = 0.001;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_max_depth_change = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_max_depth_change = 0.02;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_max_depth_change", "double", 0, "The depth in meters change threshold for computing object borders", "", &OrganizedMultiPlaneSegmentationConfig::normal_max_depth_change)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_max_depth_change", "double", 0, "The depth in meters change threshold for computing object borders", "", &OrganizedMultiPlaneSegmentationConfig::normal_max_depth_change)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_angle_threshold = 0.01;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_angle_threshold = 45.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_angle_threshold = 2.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_angle_threshold", "double", 0, "The tolerance in degrees for difference in normal direction between neighboring points, to be considered part of same plane", "", &OrganizedMultiPlaneSegmentationConfig::normal_angle_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_angle_threshold", "double", 0, "The tolerance in degrees for difference in normal direction between neighboring points, to be considered part of same plane", "", &OrganizedMultiPlaneSegmentationConfig::normal_angle_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_distance_threshold = 0.001;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_distance_threshold = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_distance_threshold = 0.02;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_distance_threshold", "double", 0, "The tolerance in meters for difference in perpendicular distance to the plane between neighboring points, to be considered part of same plane", "", &OrganizedMultiPlaneSegmentationConfig::normal_distance_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_distance_threshold", "double", 0, "The tolerance in meters for difference in perpendicular distance to the plane between neighboring points, to be considered part of same plane", "", &OrganizedMultiPlaneSegmentationConfig::normal_distance_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.normal_smooth_size = 1.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.normal_smooth_size = 100.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.normal_smooth_size = 30.0;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_smooth_size", "double", 0, "The factor which influences the size of the area used to smooth normals", "", &OrganizedMultiPlaneSegmentationConfig::normal_smooth_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("normal_smooth_size", "double", 0, "The factor which influences the size of the area used to smooth normals", "", &OrganizedMultiPlaneSegmentationConfig::normal_smooth_size)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.euclidean_distance_threshold = 0.001;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.euclidean_distance_threshold = 0.1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.euclidean_distance_threshold = 0.02;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("euclidean_distance_threshold", "double", 0, "Max distance for two objects to be considered as separated", "", &OrganizedMultiPlaneSegmentationConfig::euclidean_distance_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<double>("euclidean_distance_threshold", "double", 0, "Max distance for two objects to be considered as separated", "", &OrganizedMultiPlaneSegmentationConfig::euclidean_distance_threshold)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.plane_minimum_points = 1000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.plane_minimum_points = 20000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.plane_minimum_points = 2000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("plane_minimum_points", "int", 0, "Minimum points count for a cluster to be consider as a plane", "", &OrganizedMultiPlaneSegmentationConfig::plane_minimum_points)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("plane_minimum_points", "int", 0, "Minimum points count for a cluster to be consider as a plane", "", &OrganizedMultiPlaneSegmentationConfig::plane_minimum_points)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.object_minimum_points = 1;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.object_minimum_points = 5000;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.object_minimum_points = 200;
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("object_minimum_points", "int", 0, "Minimum points count for a cluster to be consider as an object", "", &OrganizedMultiPlaneSegmentationConfig::object_minimum_points)));
//#line 290 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::ParamDescription<int>("object_minimum_points", "int", 0, "Minimum points count for a cluster to be consider as an object", "", &OrganizedMultiPlaneSegmentationConfig::object_minimum_points)));
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 245 "/opt/ros/kinetic/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(OrganizedMultiPlaneSegmentationConfig::AbstractGroupDescriptionConstPtr(new OrganizedMultiPlaneSegmentationConfig::GroupDescription<OrganizedMultiPlaneSegmentationConfig::DEFAULT, OrganizedMultiPlaneSegmentationConfig>(Default)));
//#line 366 "/opt/ros/kinetic/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<OrganizedMultiPlaneSegmentationConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__);
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__);
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__);
    }
    std::vector<OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<OrganizedMultiPlaneSegmentationConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    OrganizedMultiPlaneSegmentationConfig __max__;
    OrganizedMultiPlaneSegmentationConfig __min__;
    OrganizedMultiPlaneSegmentationConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const OrganizedMultiPlaneSegmentationConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static OrganizedMultiPlaneSegmentationConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &OrganizedMultiPlaneSegmentationConfig::__getDescriptionMessage__()
  {
    return __get_statics__()->__description_message__;
  }

  inline const OrganizedMultiPlaneSegmentationConfig &OrganizedMultiPlaneSegmentationConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }

  inline const OrganizedMultiPlaneSegmentationConfig &OrganizedMultiPlaneSegmentationConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }

  inline const OrganizedMultiPlaneSegmentationConfig &OrganizedMultiPlaneSegmentationConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }

  inline const std::vector<OrganizedMultiPlaneSegmentationConfig::AbstractParamDescriptionConstPtr> &OrganizedMultiPlaneSegmentationConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<OrganizedMultiPlaneSegmentationConfig::AbstractGroupDescriptionConstPtr> &OrganizedMultiPlaneSegmentationConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const OrganizedMultiPlaneSegmentationConfigStatics *OrganizedMultiPlaneSegmentationConfig::__get_statics__()
  {
    const static OrganizedMultiPlaneSegmentationConfigStatics *statics;

    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = OrganizedMultiPlaneSegmentationConfigStatics::get_instance();

    return statics;
  }

//#line 27 "/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg"
      const int OrganizedMultiPlaneSegmentation_PlaneCoefficientComparator = 0;
//#line 28 "/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg"
      const int OrganizedMultiPlaneSegmentation_EuclideanPlaneCoefficientComparator = 1;
//#line 29 "/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg"
      const int OrganizedMultiPlaneSegmentation_RGBPlaneCoefficientComparator = 2;
//#line 30 "/home/awais/catkin_ws/src/ros_object_analytics/object_analytics_nodelet/cfg/OrganizedMultiPlaneSegmentation.cfg"
      const int OrganizedMultiPlaneSegmentation_EdgeAwarePlaneComparator = 3;
}

#undef DYNAMIC_RECONFIGURE_FINAL

#endif // __ORGANIZEDMULTIPLANESEGMENTATIONRECONFIGURATOR_H__
