(cl:defpackage moving_object_msgs-msg
  (:use )
  (:export
   "<MOVINGOBJECT>"
   "MOVINGOBJECT"
   "<MOVINGOBJECTSTAMPED>"
   "MOVINGOBJECTSTAMPED"
   "<MOVINGOBJECTSINFRAME>"
   "MOVINGOBJECTSINFRAME"
   "<SOCIALOBJECT>"
   "SOCIALOBJECT"
   "<SOCIALOBJECTSINFRAME>"
   "SOCIALOBJECTSINFRAME"
  ))

