// Generated by gencpp from file moving_object_msgs/MovingObjectStamped.msg
// DO NOT EDIT!


#ifndef MOVING_OBJECT_MSGS_MESSAGE_MOVINGOBJECTSTAMPED_H
#define MOVING_OBJECT_MSGS_MESSAGE_MOVINGOBJECTSTAMPED_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <moving_object_msgs/MovingObject.h>

namespace moving_object_msgs
{
template <class ContainerAllocator>
struct MovingObjectStamped_
{
  typedef MovingObjectStamped_<ContainerAllocator> Type;

  MovingObjectStamped_()
    : header()
    , object()  {
    }
  MovingObjectStamped_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , object(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::moving_object_msgs::MovingObject_<ContainerAllocator>  _object_type;
  _object_type object;





  typedef boost::shared_ptr< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> const> ConstPtr;

}; // struct MovingObjectStamped_

typedef ::moving_object_msgs::MovingObjectStamped_<std::allocator<void> > MovingObjectStamped;

typedef boost::shared_ptr< ::moving_object_msgs::MovingObjectStamped > MovingObjectStampedPtr;
typedef boost::shared_ptr< ::moving_object_msgs::MovingObjectStamped const> MovingObjectStampedConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace moving_object_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'moving_object_msgs': ['/home/awais/catkin_ws/src/ros_moving_object/moving_object_msgs/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f1fc9e196e417c4282fa9c2339291e16";
  }

  static const char* value(const ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf1fc9e196e417c42ULL;
  static const uint64_t static_value2 = 0x82fa9c2339291e16ULL;
};

template<class ContainerAllocator>
struct DataType< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "moving_object_msgs/MovingObjectStamped";
  }

  static const char* value(const ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# Copyright (c) 2017 Intel Corporation\n\
#\n\
# Licensed under the Apache License, Version 2.0 (the \"License\");\n\
# you may not use this file except in compliance with the License.\n\
# You may obtain a copy of the License at\n\
#\n\
#      http://www.apache.org/licenses/LICENSE-2.0\n\
#\n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS,\n\
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\
# See the License for the specific language governing permissions and\n\
# limitations under the License.\n\
\n\
Header header\n\
moving_object_msgs/MovingObject object\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: moving_object_msgs/MovingObject\n\
# Copyright (c) 2017 Intel Corporation\n\
#\n\
# Licensed under the Apache License, Version 2.0 (the \"License\");\n\
# you may not use this file except in compliance with the License.\n\
# You may obtain a copy of the License at\n\
#\n\
#      http://www.apache.org/licenses/LICENSE-2.0\n\
#\n\
# Unless required by applicable law or agreed to in writing, software\n\
# distributed under the License is distributed on an \"AS IS\" BASIS,\n\
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.\n\
# See the License for the specific language governing permissions and\n\
# limitations under the License.\n\
\n\
int32 id                           # Object ID\n\
string type                        # The object type detected in this roi\n\
float32 probability                # The detection probability of object in this roi\n\
sensor_msgs/RegionOfInterest roi   # region of interest\n\
geometry_msgs/Point32 min          # min and max locate the diagonal of a bounding-box of the detected object whose\n\
geometry_msgs/Point32 max          # x, y and z axis parellel to the axises correspondingly in camera coordinates\n\
geometry_msgs/Point   velocity     # The velocity with which the roi moves.\n\
================================================================================\n\
MSG: sensor_msgs/RegionOfInterest\n\
# This message is used to specify a region of interest within an image.\n\
#\n\
# When used to specify the ROI setting of the camera when the image was\n\
# taken, the height and width fields should either match the height and\n\
# width fields for the associated image; or height = width = 0\n\
# indicates that the full resolution image was captured.\n\
\n\
uint32 x_offset  # Leftmost pixel of the ROI\n\
                 # (0 if the ROI includes the left edge of the image)\n\
uint32 y_offset  # Topmost pixel of the ROI\n\
                 # (0 if the ROI includes the top edge of the image)\n\
uint32 height    # Height of ROI\n\
uint32 width     # Width of ROI\n\
\n\
# True if a distinct rectified ROI should be calculated from the \"raw\"\n\
# ROI in this message. Typically this should be False if the full image\n\
# is captured (ROI not used), and True if a subwindow is captured (ROI\n\
# used).\n\
bool do_rectify\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point32\n\
# This contains the position of a point in free space(with 32 bits of precision).\n\
# It is recommeded to use Point wherever possible instead of Point32.  \n\
# \n\
# This recommendation is to promote interoperability.  \n\
#\n\
# This message is designed to take up less space when sending\n\
# lots of points at once, as in the case of a PointCloud.  \n\
\n\
float32 x\n\
float32 y\n\
float32 z\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.object);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct MovingObjectStamped_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::moving_object_msgs::MovingObjectStamped_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "object: ";
    s << std::endl;
    Printer< ::moving_object_msgs::MovingObject_<ContainerAllocator> >::stream(s, indent + "  ", v.object);
  }
};

} // namespace message_operations
} // namespace ros

#endif // MOVING_OBJECT_MSGS_MESSAGE_MOVINGOBJECTSTAMPED_H
